export const API = {
  USER: {
    REGISTER: "/api/user/register",
    LOGIN: "/api/user/login",
    GET_ALL: "/api/user",
    GET_PROFILE: (id: string) => `/api/user/${id}`,
    GET_MY_PROFILE: "/api/user/profile",
    UPDATE_MY_PROFILE: "/api/user/profile",
    REQUEST_PASSWORD_RESET: "/api/user/request-password-reset",
    RESET_PASSWORD: (token: string) => `/api/user/reset-password/${token}`,
    CHANGE_PASSWORD: "/api/user/change-password",
  },
  BUSINESS: {
    REGISTER: "/api/business/register",
    LOGIN: "/api/business/login",
    GET_ALL: "/api/business/admin/all",
    UPLOAD_DOC: "/api/business/upload-document",
    APPROVE: (id: string) => `/api/business/admin/approve/${id}`,
    REJECT: (id: string) => `/api/business/admin/reject/${id}`,
    GET_PROFILE: "/api/business/profile",
    UPDATE_PROFILE: "/api/business/profile/edit",
  },
  ADMIN: {
    GET_ALL_USERS: "/api/user",
    GET_ALL_BUSINESSES: "/api/business/admin/all",
    APPROVE_BUSINESS: (id: string) => `/api/business/admin/approve/${id}`,
    REJECT_BUSINESS: (id: string) => `/api/business/admin/reject/${id}`,
  },
  CATEGORY: {
    GET_ALL: "/api/categories",
    GET_BY_ID: (id: string) => `/api/categories/${id}`,
    CREATE: "/api/categories",
    UPDATE: (id: string) => `/api/categories/${id}`,
    DELETE: (id: string) => `/api/categories/${id}`,
  },
  PRODUCT: {
    GET_ALL: "/api/products",
    GET_BY_ID: (id: string) => `/api/product/${id}`,
    GET_BY_CATEGORY: (categoryId: string) =>
      `/api/product/category/${categoryId}`,
    GET_BUSINESS: "/api/product/business",
    CREATE: "/api/product",
    UPDATE: (id: string) => `/api/product/${id}`,
    DELETE: (id: string) => `/api/product/${id}`,
  },
  CART: {
    GET: "/api/cart",
    ADD: "/api/cart/add",
    UPDATE: (productId: string) => `/api/cart/item/${productId}`,
    REMOVE: (productId: string) => `/api/cart/item/${productId}`,
    CLEAR: "/api/cart/clear",
    COUNT: "/api/cart/count",
  },
  ORDER: {
    CREATE: "/api/order",
    GET_USER: "/api/order/user",
    GET_BUSINESS: "/api/order/business/orders",
    GET_BY_ID: (orderId: string) => `/api/order/${orderId}`,
    UPDATE_STATUS: (orderId: string) => `/api/order/${orderId}/status`,
    UPDATE_PAYMENT: (orderId: string) => `/api/order/${orderId}/payment`,
  },
  PAYMENT: {
    KHALTI_INITIATE: "/api/payments/khalti/initiate",
    KHALTI_VERIFY: "/api/payments/khalti/verify",
    KHALTI_WEBHOOK: "/api/payments/khalti/webhook",
    GET_BY_ORDER: (orderId: string) => `/api/payments/order/${orderId}`,
    GET_USER: "/api/payments/user",
    GET_ALL: "/api/payments/admin/all",
  },
  WALLET: {
    USER_BALANCE: "/api/wallets/balance",
    USER_TRANSACTIONS: "/api/wallets/transactions",
    BUSINESS_BALANCE: "/api/wallets/business/balance",
    BUSINESS_TRANSACTIONS: "/api/wallets/business/transactions",
  },
};
